name: Deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'
        bundler-cache: false  # Disable cache to avoid stale gem issues

    - name: Fix Bundler and install dependencies
      run: |
        gem uninstall bundler -aIx || true
        gem install bundler -v 2.4.22
        bundle _2.4.22_ install

    - name: Install extra deps (mermaid-cli)
      run: |
        npm install -g @mermaid-js/mermaid-cli

    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        {
          if [[ "${GITHUB_REF}" == refs/pull/*/merge ]]; then
            echo "SRC_BRANCH=${GITHUB_HEAD_REF}"
            echo "NO_PUSH=--no-push"
          elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}"
          fi
          echo "DEPLOY_BRANCH=gh-pages"
        } >> "$GITHUB_OUTPUT"

    - name: Deploy website
      run: |
        yes | bash bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }} \
          --src ${{ steps.setup.outputs.SRC_BRANCH }} \
          --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}
